INTEGRATION_KEY = '*******************'
EBANX_API_PAYMENT_URL = 'https://sandbox.ebanx.com/ws/direct'
EBANX_API_CANCEL_URL = 'https://sandbox.ebanx.com/ws/cancel'
EBANX_API_TOKEN_URL = 'https://sandbox.ebanx.com/ws/token'
DATABASE = 'test-project/sqlite.db'
